### PR TITLE
Switch user from _cscreen to cscreen

### LINKED ISSUE #7: Username `_cscreen` is invalid for most modern distros
During installation on SLES 15.5 `useradd` is complaining about the fact that the username `_cscreen` is invalid. This is because most modern distros have tightened the requirements for usernames to only allow less characters.

```
sconsole1:~ # zypper in system-user-cscreen
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...
Paketabhängigkeiten werden aufgelöst...

Das folgende NEUE Paket wird installiert:
  system-user-cscreen

Das folgende Paket wird vom Anbieter nicht unterstützt:
  system-user-cscreen

1 neues Paket zu installieren.
Gesamtgröße des Downloads: 0 B. Bereits im Cache gespeichert: 11,5 KiB. Nach der Operation werden zusätzlich 103,0 B belegt.
Continue? [j/n/v/...? zeigt alle Optionen] (j): 
Im Cache system-user-cscreen-1.5-150500.41.1.noarch.rpm                                                                                                                                                                                                   (1/1),  11,5 KiB    

Überprüfung auf Dateikonflikte läuft: ................................................................................................................................................................................................................................[fertig]
/usr/sbin/useradd -r -c cscreen daemon user -d /var/lib/cscreen -U -u _cscreen _cscreen -s /bin/bash
useradd: invalid user ID '_cscreen'
error: %prein(system-user-cscreen-1.5-150500.41.1.noarch) scriptlet failed, exit status 1
error: system-user-cscreen-1.5-150500.41.1.noarch: install failed
(1/1) Installieren: system-user-cscreen-1.5-150500.41.1.noarch .......................................................................................................................................................................................................[Fehler]
Installation von system-user-cscreen-1.5-150500.41.1.noarch fehlgeschlagen:
Fehler: Subprocess failed. Error: RPM fehlgeschlagen: Kommando mit Status 1 beendet.
Abbrechen, wiederholen, ignorieren? [a/w/i] (a): a
Während oder nach der Installation/dem Entfernung von Paketen ist ein Problem aufgetreten:
Die Installation wurde gemäß Anweisung abgebrochen.
In der Fehlermeldung oben finden Sie einen entsprechenden Hinweis.
sconsole1:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #7

### CODE REVIEW

**Comment by olafhering** [comment]
This can not be merged unless orthos starts to use the name which lacks the underscore...

**Comment by SchoolGuy** [comment]
@olafhering This will be the case.

**Comment by SchoolGuy** [comment]
PR is open: https://github.com/openSUSE/orthos2/pull/233

**Comment by watologo1** [comment]
Sigh, I remember the former cscreen maintainer (Lars Vogdt) wanted to have an underscore, due to some policy that got introduced (by debian?), to identify system/package users.
No idea whether this policy makes sense or is widespread nowadays..., why should we change default name for _cscreen user?
Is there anything which does not work using _cscreen?

**Pull request merged**
